apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deployment
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: app-services
  source:
    repoURL: 'https://github.com/dpetrocelli/argocd-apps.git'
    targetRevision: 'main'  # Replace 'HEAD' with 'main' or another branch/tag/commit
    chart: apps/charts/mynginx
  destination:
    name: in-cluster
    namespace: apps-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
