apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deployment
  namespace: argocd
  finalizers:
  - resources-finalizer.argoproj.io
spec:
  project: app-services
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 'latest'
    chart: nginx
  destination:
    name: in-cluster
    namespace: apps-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
