apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deployment
  namespace: argocd
  finalizers:
  - resources-finalizer.argoproj.io
spec:
  project: app-services
  source:
    repoURL: 'https://github.com/dpetrocelli/argocd-apps.git'
    targetRevision: 'main'  # Ensure this is the default branch if specific commits/tags don't work
    chart: charts/mynginx
  destination:
    name: in-cluster
    namespace: apps-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
