---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.argocd.10.net.ar`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
    - match: Host(`argocd.10.net.ar`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
      # middlewares:
      #   - name: default-headers
  tls:
    secretName: argocd-dev-cert
