apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress
  namespace: services-traefik
  labels:
    app.kubernetes.io/instance: traefik-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-28.0.0
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
    - name: websecure
      port: 443
      targetPort: websecure
      protocol: TCP
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
  selector:
    app.kubernetes.io/instance: traefik-ingress-services-traefik
    app.kubernetes.io/name: traefik
