apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-services
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: '1.14.5'
    chart: cert-manager
    helm:
      values: |
        installCRDs: false
        replicaCount: 3
        extraArgs:
          - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
          - --dns01-recursive-nameservers-only
        podDnsPolicy: None
        podDnsConfig:
          nameservers:
            - "1.1.1.1"
            - "9.9.9.9"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: services-cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  hooks:
    - name: install-crds
      type: PreSync
      helm:
        releaseName: cert-manager-crds
        chart:
          spec:
            chart: "cert-manager"
            sourceRef:
              repoURL: "https://charts.jetstack.io"
              path: "/charts/cert-manager"
              targetRevision: "1.14.5"
            version: "v1.14.5"
            hooks:
              - name: install-crds
                events: [ "pre-install", "pre-upgrade" ]
                manifest: |
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: cert-manager-webhook-ca
                    namespace: cert-manager
                  data:
                    ca.crt: |
                      {{ .Files.Get "templates/webhook/ca.crt" | b64enc | quote }}
