# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   annotations:
#     argocd.argoproj.io/sync-wave: "2"
#   name: backend
#   namespace: argocd
# spec:
#   source:
#     path: services/charts/rabbitmq
#     repoURL: 'https://github.com/dpetrocelli/argocd-apps'
#     targetRevision: HEAD
#   destination:
#     namespace: services
#     server: 'https://kubernetes.default.svc'
#   project: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     retry:
#       limit: 5
#       backoff:
#         duration: 5s
#         maxDuration: 3m0s
#         factor: 2
#     syncOptions:
#       - CreateNamespace=true
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
spec:
  project: root-application
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '6.1.1'
    chart: rabbitmq-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
