apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: my-project2
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '4.2.10'
    chart: rabbitmq-cluster-operator
  destination:
    name: in-cluster
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true