apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-services
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '10.0.6'
    chart: redis-cluster
    helm:
      values: |
        cluster:
          nodes: 3
          replicas: 1
  destination:
    name: in-cluster
    namespace: services-redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

