apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infra-services
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    targetRevision: '28.0.0'
    chart: traefik
    helm:
      values: |
        globalArguments:
          - "--global.sendanonymoususage=false"
          - "--global.checknewversion=false"
        additionalArguments:
          - "--serversTransport.insecureSkipVerify=true"
          - "--log.level=DEBUG"
          - "--api"
          - "--api.insecure"
          - "--entrypoints.web.address=:80"
          - "--entrypoints.tcpep.address=:8000"
          - "--entrypoints.udpep.address=:9000/udp"
          - "--providers.kubernetescrd"
        deployment:
          enabled: true
          replicas: 1
        ports:
          web:
            port: 80
            expose: true
            exposedPort: 80
            protocol: TCP
          admin:
            port: 8080
            expose: true
            exposedPort: 8080
            protocol: TCP
          tcpep:
            port: 8000
            expose: true
            exposedPort: 8000
            protocol: TCP
          udpep:
            port: 9000
            expose: true
            exposedPort: 9000
            protocol: UDP
        service:
          spec:
            type: LoadBalancer
            ports:
              - name: web
                port: 80
                targetPort: 80
                protocol: TCP
              - name: admin
                port: 8080
                targetPort: 8080
                protocol: TCP
              - name: tcpep
                port: 8000
                targetPort: 8000
                protocol: TCP
              - name: udpep
                port: 9000
                targetPort: 9000
                protocol: UDP
        ingressRoute:
          dashboard:
            enabled: true
        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: traefik-external
          kubernetesIngress:
            enabled: true
        ingressClass:
          enabled: true
          isDefaultClass: true
          name: traefik-external
        rbac:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: services-traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
