apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress
  namespace: argocd
spec:
  project: infra-services
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    targetRevision: '28.0.0'
    chart: traefik
    helm:
      values: |
        globalArguments:
          - "--global.sendanonymoususage=false"
          - "--global.checknewversion=false"

        additionalArguments:
          - "--serversTransport.insecureSkipVerify=true"
          - "--log.level=INFO"

        deployment:
          enabled: true
          replicas: 1
          annotations: {}
          podAnnotations: {}
          additionalContainers: []
          initContainers: []

        ports:
          web:
            redirectTo:
              port: websecure
          websecure:
            tls:
              enabled: true

        ingressRoute:
          dashboard:
            enabled: true
            annotations: {}
            labels: {}
            matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
            entryPoints: ["traefik"]
            middlewares: []
            tls: {}

        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: traefik-external
          kubernetesIngress:
            enabled: true
            publishedService:
              enabled: false

        ingressClass:
          enabled: true
          isDefaultClass: true
          name: traefik-external

        rbac:
          enabled: true

        service:
          enabled: true
          type: LoadBalancer
          annotations: {}
          labels: {}
          loadBalancerSourceRanges: []
          externalIPs: []
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: services-traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard-ingress
  namespace: services-traefik
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
  - host: "traefik-dashboard.10.net.ar"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik
            port:
              number: 8080
  tls:
  - hosts:
    - "traefik-dashboard.10.net.ar"
    secretName: traefik-tls-secret

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: traefik-ingress
#   namespace: argocd
# spec:
#   project: infra-services
#   source:
#     repoURL: 'https://helm.traefik.io/traefik'
#     targetRevision: '28.0.0'
#     chart: traefik
#     helm:
#       values: |
#         ports:
#           web:
#             redirectTo:
#               port: websecure
#           websecure:
#             tls:
#               enabled: true
#               certResolver: myresolver
#         additionalArguments:
#           - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
#           - "--certificatesresolvers.myresolver.acme.email=dmpetrocelli@gmail.com"
#           - "--certificatesresolvers.myresolver.acme.storage=acme.json"
#         ingressRoute:
#           dashboard:
#             enabled: true
#             domain: "traefik-dashboard.10.net.ar"
#         providers:
#           kubernetesCRD:
#             enabled: true
#           kubernetesIngress:
#             enabled: true
#             ingressClass: traefik-cert-manager
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: services-traefik
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: traefik-dashboard-ingress
#   namespace: services-traefik
#   annotations:
#     kubernetes.io/ingress.class: "traefik"
#     traefik.ingress.kubernetes.io/router.entrypoints: websecure
# spec:
#   rules:
#   - host: "traefik-dashboard.10.net.ar"
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: traefik
#             port:
#               number: 8080
#   tls:
#   - hosts:
#     - "traefik-dashboard.10.net.ar"
#     secretName: traefik-tls-secret