apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infra-services
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    targetRevision: '28.0.0'
    chart: traefik
    helm:
      values: |
        globalArguments:
          - "--global.sendanonymoususage=false"
          - "--global.checknewversion=false"
        additionalArguments:
          - "--serversTransport.insecureSkipVerify=true"
          - "--log.level=INFO"
          - "--entrypoints.amqp.address=:5672"
          - "--entrypoints.mysql.address=:3306"
        deployment:
          enabled: true
          replicas: 1
        ports:
          web:
            port: 80
            protocol: TCP
            expose: 
              enabled: true
          websecure:
            port: 443
            protocol: TCP
            tls:
              enabled: true
            expose: 
              enabled: true
          mqtt:
            port: 1883
            protocol: TCP
            expose: 
              enabled: true
          amqp:
            port: 5672
            protocol: TCP
            expose: 
              enabled: true
        service:
          type: LoadBalancer
          spec:
            ports:
              - name: web
                port: 80
                protocol: TCP
              - name: websecure
                port: 443
                protocol: TCP
              - name: mqtt
                port: 1883
                protocol: TCP
              - name: amqp
                port: 5672
                protocol: TCP
        ingressRoute:
          dashboard:
            enabled: true
        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: traefik-external
          kubernetesIngress:
            enabled: true
        ingressClass:
          enabled: true
          isDefaultClass: true
          name: traefik-external
        rbac:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: services-traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
