
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: rabbitmq-epmd
  namespace: services-rabbitmq
spec:
  entryPoints:
    - epmd
  routes:
  - match: HostSNI(`epmd-rabbitmq.10.net.ar`)
    services:
    - name: rabbitmq
      port: 4369
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: rabbitmq-amqp
  namespace: services-rabbitmq
spec:
  entryPoints:
    - amqp
  routes:
  - match: HostSNI(`epmd-rabbitmq.10.net.ar`)
    services:
    - name: rabbitmqcluster-prod
      port: 5672

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: services-rabbitmq
  namespace: services-rabbitmq
  annotations: 
    kubernetes.io/ingress.class: "traefik-external"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.rabbitmq-gui.10.net.ar`)
      kind: Rule
      services:
        - name: rabbitmqcluster-prod
          port: 15672
    - match: Host(`rabbitmq-gui.10.net.ar`)
      kind: Rule
      services:
        - name: rabbitmqcluster-prod
          port: 15672
  tls:
    secretName: rabbitmq-dev-cert
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: redis
  namespace: services-redis

spec:
  entryPoints:
    - redis

  routes:
  - match: HostSNI(`*`)
    services:
    - name: redis-cluster
      port: 6379