globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"
  - "--entrypoints.amqp.address=:5672"
  - "--entrypoints.mysql.address=:3306"

deployment:
  enabled: true
  replicas: 1

ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true
  amqp:
    port: 5672
    expose: true
    exposedPort: 5672
    protocol: TCP
  mysql:
    port: 3306
    expose: true
    exposedPort: 3306
    protocol: TCP

ingressRoute:
  dashboard:
    enabled: true
    matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    entryPoints: ["traefik"]

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
  kubernetesIngress:
    enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik-external

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
