---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-dev-cert
  namespace: argocd
spec:
  secretName: argocd-dev-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.10.net.ar"
  dnsNames:
  - "10.net.ar"
  - "*.10.net.ar"
